### ISSUE TITLE
How effective/safe is the use of UV-C 254nm as opposed to 265nm?

### ISSUE THREAD

**Issue by wzbernstein** [MicrosoftDocs/Hololens#10]
Can you please comment on UV-C 254nm radiation for sterilization?  There is a higher variety of 254nm solutions on the market.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b9efc6-78cd-1f1e-bcd5-3e02130b7bd9
* Version Independent ID: 9ce2e642-96f3-ec9c-e8bd-1e5c8846d1e1
* Content: [HoloLens 2 cleaning FAQ](https://docs.microsoft.com/en-us/hololens/hololens2-maintenance)
* Content Source: [hololens/hololens2-maintenance.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens2-maintenance.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by evmill** [comment]
Hello @wzbernstein I recently had a conversation with someone about this who I just met yesterday and asked them your question. 
"Regarding question about UV-C 254nm, the answer is not recommended. The reason is: different from recommended LED based UVC sanitizing (250~280nm), quartz lamp based 254nm UVC light has broader spectrum (180-315nm); significant portion is in 160-240nm band which can generate ozone, a gas being corrosive to plastic materials used in HL2."

**Comment by wzbernstein** [comment]
Ah.. thanks for sharing!
