### ISSUE TITLE
Format and/or Example of the fully qualified AAD account name for "except 1 AAD"

### ISSUE THREAD

**Issue by cdonohoe** [MicrosoftDocs/Hololens#12]
[Enter feedback here]

In the section 
https://docs.microsoft.com/en-us/hololens/hololens-global-assigned-access-kiosk#can-i-create-a-configuration-where-global-applies-to-everyone-except-1-aad-account-or-aad-group

The documentation states to use <Account>AzureAD\<!-fully qualified AAD account name></Account> 

When we add the group name as follows AzureAD\GroupDisplayName it does not apply the alternate profile apps.
we also appended @tenantdomain to no avail.

Can you clarify what exactly and the format to be used for the account name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4def914f-6010-dcef-aec1-b455bec1bca6
* Version Independent ID: d499a5be-237a-59aa-8296-f32c5d4318d7
* Content: [Global Assigned Access](https://docs.microsoft.com/en-us/hololens/hololens-global-assigned-access-kiosk)
* Content Source: [hololens/hololens-global-assigned-access-kiosk.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-global-assigned-access-kiosk.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **v-evmill**

**Comment by evmill** [comment]
You're looking for something like this: 
`<Account>AzureAD\contosouser@contoso.onmicrosoft.com</Account>`

**Comment by cdonohoe** [comment]
That doesn't work I am sorry to say.

Tried it with <Account>AzureAD\**groupname**@contoso.onmicrosoft.com</Account> obviously our tenant name not contoso :)

**Comment by evmill** [comment]
Sorry about that, didn't realize you were going for AAD group. 
Instead you'll need something like this:
`<UserGroup Type="AzureActiveDirectoryGroup" Name="050ed07d-e123-48e6-a9be-c3a0e907553d" />`
The Name field is the Object ID of your group. So if you are using Intune then you'd navigate to https://endpoint.microsoft.com/#home , groups, select your group, and copy the Object ID. 

Let me know if that does it.

**Comment by cdonohoe** [comment]
Okay will try that, and provide update here.

Intune issues reported on MS admin center and it is impacting our tenant so will try this once we are back online.

**Comment by cdonohoe** [comment]
Hi unfortunately that did not work. 

The XML is landing correctly and the global config has setup the correct apps in the kiosk and we double checked the device is a member of the AAD group but it still is not removing the apps we have commented out in the second profile.  Can you carry out a test and see if the group lookup is happening or if something else needs to be tweaked.

**Comment by evmill** [comment]
Hello checking back in. So I'm not sure which of these two issues you're running into. And given what I'm assuming is our time difference I'll ask about both. 

First off I want to ask if when booting into the device you see the Kiosk at all. 

If you're seeing the Kiosk with one user, and then signing out and seeing the Kiosk again with the excluded user this may be a bug that Insider will be receiving the fix for shortly. You can confirm this is the case if you were to reboot the device and sign into the excluded user, not see Kiosk, and then sign into the user who should receive kiosk and they inherit the excluded state. 

If you aren't seeing Kiosk at all. Regardless of reboot and logging into the user who should see the Kiosk, then it may be the group that needs modifying. 

Also I can help a little differently than test it out. Go ahead and [file a bug with Feedback Hub from the HoloLens 2](https://docs.microsoft.com/en-us/hololens/hololens-feedback). And let me know the name of your bug. 
From the Dev team: "Request the customer to file a bug describing the exact configuration they are trying to apply and the issues they observe". Give as much detail as possible and we'll do the best we can to help out. Use full telemetry.

**Comment by cdonohoe** [comment]
“Global Assigned Access policy on HoloLens2” at ~09:58 UTC is the name of the bug report.

Yes the Global kiosk profile is landing just not the alternate profile.

**Comment by evmill** [comment]
I've passed it along to the Dev team.

**Comment by cdonohoe** [comment]
thanks 👍

**Comment by evmill** [comment]
Hey, we got the bug but noticed we didn't get the full information. The dev team would like it if you could file a new bug under a specific category. 
"Please request customer to file bug in **enterprise management > device category** and if they are willing to share the assigned access configuration, I can take a look at it to determine if configuration is correct or not." You could directly attach that to the bug if you like (just copy it to your device and then attach the file it asks if you have picture, files, or repro videos). Or find some other way to share the file.

**Comment by cdonohoe** [comment]
This has been submitted ("enterprise management > device category") and we attached the xml file to the logs.  Thanks

**Comment by evmill** [comment]
Hello again, 
I think if you may find that if you update your device to today's windows insider build (or download the latest build from
[https://aka.ms/hololens2previewdownload](https://aka.ms/hololens2previewdownload) and flash your device) and try again things should be working as expected.
