### ISSUE TITLE
Problems with "Old" and "New" AUMIDs for Settings

### ISSUE THREAD

**Issue by ARGs-code** [MicrosoftDocs/Hololens#59]
[Enter feedback here]
What is the difference between the "old" and "new" AUMIDs for Settings and Edge?

I have tried to use both old and new AUMIDs for the settings application in a HoloLens multi application Kiosk and neither AUMID results in the Settings application being accessible by the user in Kiosk Mode. All other AUMIDs on this page appear to work as intended and noted.

Can you please provide additional guidance on why there are two entries for the Settings Application and which is preferable to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11c1d5ab-e0ff-9844-71a6-da2139849b01
* Version Independent ID: de75ca90-22c8-1165-08f0-ce486fc1fd3e
* Content: [HoloLens kiosk reference information](https://docs.microsoft.com/en-us/hololens/hololens-kiosk-reference#hololens-application-user-model-ids-aumids)
* Content Source: [hololens/hololens-kiosk-reference.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-kiosk-reference.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **v-evmill**

**Comment by evmill** [comment]
Hello @ARGs-code 
In May we release [Windows Holographic, version 21H1](https://docs.microsoft.com/en-us/hololens/hololens-release-notes#windows-holographic-version-21h1) which introduced newer apps for both Settings and Edge. While on the surface, for a user who updated their device they wouldn't see the difference on the back end they are technically new apps. Because of this it requires a different AUMID. 

Depending on your OS version of the devices you are deploying the Kiosk mode to you would use the app version that would match. My personal recommendation is to use both the old and the new versions. https://docs.microsoft.com/en-us/hololens/hololens-release-notes#use-the-new-settings-and-edge-apps-in-kiosk-modes

**Comment by ARGs-code** [comment]
@evmill Thank you for this guidance and prompt response. I appreciate it!
