### ISSUE TITLE
Can not log into the Microsoft Mesh platforms by Hololens2? 

### ISSUE THREAD

**Issue by puqigo** [MicrosoftDocs/Hololens#92]
Hi,

May I ask why I could not log into the Microsoft Mesh application since this Tuesday? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e67982e-6e73-e5cd-04eb-3c80568a99be
* Version Independent ID: 75498529-c75a-cdb8-43aa-7a87aa523aa3
* Content: [Give us feedback](https://learn.microsoft.com/en-us/hololens/hololens-feedback)
* Content Source: [hololens/hololens-feedback.md](https://github.com/MicrosoftDocs/Hololens/blob/public/hololens/hololens-feedback.md)
* Product: **hololens**
* Technology: **windows**
* GitHub Login: @evmill
* Microsoft Alias: **millerevan**

**Comment by evmill** [comment]
Hi @puqigo ,
I wouldn't know why you can't log into Mesh. There could be a number of different things. If you think you're not able to login because it's a bug, try [filing a bug via feedback hub](https://learn.microsoft.com/en-us/hololens/hololens-feedback). You won't hear back but if it is an issue then it could be fixed in a future update.
If you need help getting in, or need to get in soon, try [getting support](https://learn.microsoft.com/en-us/hololens/hololens2-support) where they can walk through the issue and look at the logs from the bug you file.
Thanks,
-Evan

**Comment by puqigo** [comment]
Hi, I have reset my hololens2 twice and try it many times to log into the Mesh; however, each time, after a long wait to enter the home space. IT will show the below figure. 
<img width="675" alt="Mesh" src="https://user-images.githubusercontent.com/98409397/216730906-f164dfee-d3f0-482e-9c33-495ab6cd4163.png">
